# Generated by Django 5.1.2 on 2024-11-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_audio_description_audio_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='user',
            new_name='author',
        ),
    ]
